// user authentication types
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

// article types
export const CREATE_ARTICLE_REQUEST = "CREATE_ARTICLE_REQUEST";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_FAILED = "CREATE_ARTICLE_FAILED";

export const GET_ARTICLE_REQUEST = "GET_ARTICLE_REQUEST";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_FAILED = "GET_ARTICLE_FAILED";

export const GET_SINGLE_ARTICLE_REQUEST = "GET_SINGLE_ARTICLE_REQUEST";
export const GET_SINGLE_ARTICLE_SUCCESS = "GET_SINGLE_ARTICLE_SUCCESS";
export const GET_SINGLE_ARTICLE_FAILED = "GET_SINGLE_ARTICLE_FAILED";

// comment types
export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILED = "CREATE_COMMENT_FAILED";

export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAILED = "GET_COMMENT_FAILED";

// like types
export const CREATE_LIKE_REQUEST = "CREATE_LIKE_REQUEST";
export const CREATE_LIKE_SUCCESS = "CREATE_LIKE_SUCCESS";
export const CREATE_LIKE_FAILED = "CREATE_LIKE_FAILED";

export const GET_LIKE_REQUEST = "GET_LIKE_REQUEST";
export const GET_LIKE_SUCCESS = "GET_LIKE_SUCCESS";
export const GET_LIKE_FAILED = "GET_LIKE_FAILED";